export const env_var = {
  PYTHON_BACKEND_URL: process.env.NEXT_PUBLIC_PYTHON_BACKEND_URL,
  PYTHON_BACKEND_PORT: process.env.NEXT_PUBLIC_PYTHON_BACKEND_PORT,
  JWT_SECRET: process.env.JWT_SECRET,
  DATABASE_KEY: process.env.DATABASE_KEY,
  ID_ENCRYPTION_SECRET: process.env.ID_ENCRYPTION_SECRET
};
